// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShopOnline.DataBaseContext;

#nullable disable

namespace ShopOnline.Migrations
{
    [DbContext(typeof(DBaseContext))]
    partial class DBaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShopOnline.Models.Opiniones", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Calificacion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Calificacion");

                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Codigo");

                    b.Property<string>("Comentario")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Comentario");

                    b.Property<string>("Data1")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Data1");

                    b.Property<string>("Data2")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Data2");

                    b.Property<string>("Data3")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Data3");

                    b.Property<string>("Data4")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Data4");

                    b.HasKey("UserId");

                    b.ToTable("Opiniones");
                });

            modelBuilder.Entity("ShopOnline.Models.PrincipalStruct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Canal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Data1")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Data1");

                    b.Property<string>("Data10")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Data10");

                    b.Property<string>("Data11")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Data11");

                    b.Property<string>("Data12")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Data12");

                    b.Property<string>("Data13")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Data13");

                    b.Property<string>("Data14")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Data14");

                    b.Property<string>("Data15")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Data15");

                    b.Property<string>("Data16")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Data16");

                    b.Property<string>("Data17")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Data17");

                    b.Property<string>("Data18")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Data18");

                    b.Property<string>("Data2")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Data2");

                    b.Property<string>("Data3")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Data3");

                    b.Property<string>("Data4")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Data4");

                    b.Property<string>("Data5")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Data5");

                    b.Property<string>("Data6")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Data6");

                    b.Property<string>("Data7")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Data7");

                    b.Property<string>("Data8")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Data8");

                    b.Property<string>("Data9")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Data9");

                    b.Property<string>("Opiniones")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("OpinionesData");

                    b.Property<string>("Substructs")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SubstructsData");

                    b.HasKey("Id");

                    b.ToTable("PrincipalStructs");
                });

            modelBuilder.Entity("ShopOnline.Models.Substruct", b =>
                {
                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BreveDescripcion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("BreveDescripcion");

                    b.Property<string>("Categoria")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Categoria");

                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Codigo");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Color");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Descripcion");

                    b.Property<string>("Extra1")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Extra1");

                    b.Property<string>("Extra2")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Extra2");

                    b.Property<string>("Extra3")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Extra3");

                    b.Property<string>("Extra4")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Extra4");

                    b.Property<string>("Extra5")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Extra5");

                    b.Property<string>("Extra6")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Extra6");

                    b.Property<string>("Extra7")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Extra7");

                    b.Property<string>("Extra8")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Extra8");

                    b.Property<string>("Images")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Images");

                    b.Property<string>("LikesBase")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LikesBase");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Nombre");

                    b.Property<string>("Precio")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Precio");

                    b.Property<string>("SubCategoria")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SubCategoria");

                    b.Property<string>("Talla")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Talla");

                    b.Property<string>("TiempoOferta")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TiempoOferta");

                    b.Property<string>("Ventas")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Ventas");

                    b.Property<string>("VentasBase")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("VentasBase");

                    b.HasKey("Date");

                    b.ToTable("Substruct");
                });

            modelBuilder.Entity("ShopOnline.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
